// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: shortlink.proto

package server

import (
	"context"

	"shortlink/internal/logic"
	"shortlink/internal/svc"
	"shortlink/pb/shortlink"
)

type ShortlinkServer struct {
	svcCtx *svc.ServiceContext
	shortlink.UnimplementedShortlinkServer
}

func NewShortlinkServer(svcCtx *svc.ServiceContext) *ShortlinkServer {
	return &ShortlinkServer{
		svcCtx: svcCtx,
	}
}

func (s *ShortlinkServer) CreateShortLink(ctx context.Context, in *shortlink.ShortLinkCreateRequest) (*shortlink.ShortLinkCreateResponse, error) {
	l := logic.NewCreateShortLinkLogic(ctx, s.svcCtx)
	return l.CreateShortLink(in)
}

func (s *ShortlinkServer) UpdateShortLink(ctx context.Context, in *shortlink.ShortLinkUpdateRequest) (*shortlink.ShortLinkUpdateResponse, error) {
	l := logic.NewUpdateShortLinkLogic(ctx, s.svcCtx)
	return l.UpdateShortLink(in)
}

func (s *ShortlinkServer) PageShortLink(ctx context.Context, in *shortlink.ShortLinkPageRequest) (*shortlink.ShortLinkPageResponse, error) {
	l := logic.NewPageShortLinkLogic(ctx, s.svcCtx)
	return l.PageShortLink(in)
}

func (s *ShortlinkServer) DeleteShortLink(ctx context.Context, in *shortlink.ShortLinkDeleteRequest) (*shortlink.ShortLinkDeleteResponse, error) {
	l := logic.NewDeleteShortLinkLogic(ctx, s.svcCtx)
	return l.DeleteShortLink(in)
}

func (s *ShortlinkServer) ListGroupShortLinkCount(ctx context.Context, in *shortlink.ListGroupShortLinkCountRequest) (*shortlink.ListGroupShortLinkCountResponse, error) {
	l := logic.NewListGroupShortLinkCountLogic(ctx, s.svcCtx)
	return l.ListGroupShortLinkCount(in)
}
